# Site settings
title: pxwise
email: sstedman@pxwise.com
description: > # this means to ignore newlines until "baseurl:"
  Shawn Stedman's coding blog. Front End Engineer in San Francisco with a focus
  on all things Javascript. I enjoy hacking in React, Angular, Backbone, D3,
  THREE.js, Raphael.js, Node.js
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://pxwise.com" # the base hostname & protocol for your site
twitter_username: pxwise
github_username:  pxwise

# Build settings
markdown: kramdown
