# Site settings
title: pxwise
email: sstedman@pxwise.com
description: > # this means to ignore newlines until "baseurl:"
  Shawn Stedman's coding blog. Front End Engineer in San Francisco, enjoying hacking on all things Javascript, especially React, Angular, Node.js, THREE.js and D3.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pxwise.com" # the base hostname & protocol for your site
twitter_username: pxwise
github_username:  pxwise

# Build settings
markdown: kramdown

pages_list:
  Archive: '/archive'
  About: '/about'
#  Feed: '/atom.xml'

gems:
- jemoji
- jekyll-sitemap
#- jekyll-mentions
#- jekyll-redirect-from
